
---
title: "FDA Drug Recall Classifier - Modeling Report"
author: "Jannet Castaneda"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(tidymodels)
library(textrecipes)
library(readr)
library(nnet)
```

## Load and Prepare Data

```{r}
fda <- read_csv("2_data/fda_recalls_clean.csv")

# Ensure classification is a factor
fda <- fda %>%
  mutate(event_classification = as.factor(event_classification))
```

## Split Data

```{r}
set.seed(123)
split <- initial_split(fda, prop = 0.8)
train_data <- training(split)
test_data  <- testing(split)
```

## Recipe for Text Features

```{r}
recall_recipe <- recipe(event_classification ~ reason_for_recall, data = train_data) %>%
  step_tokenize(reason_for_recall) %>%
  step_stopwords(reason_for_recall) %>%
  step_tokenfilter(reason_for_recall, max_tokens = 100) %>%
  step_tfidf(reason_for_recall)
```

## Model Specification and Workflow

```{r}
lr_spec <- multinom_reg() %>%
  set_engine("nnet") %>%
  set_mode("classification")

recall_wf <- workflow() %>%
  add_recipe(recall_recipe) %>%
  add_model(lr_spec)
```

## Fit the Model

```{r}
recall_fit <- recall_wf %>%
  fit(data = train_data)
```

## Evaluate on the Test Set

```{r}
test_predictions <- predict(recall_fit, test_data, type = "prob") %>%
  bind_cols(predict(recall_fit, test_data)) %>%
  bind_cols(test_data)
```

## Confusion Matrix

```{r}
conf_mat(test_predictions, truth = event_classification, estimate = .pred_class)
```

## Accuracy and Kappa

```{r}
metrics(test_predictions, truth = event_classification, estimate = .pred_class)
```

## Manual Keyword Inspection: `"death"`

```{r}
# Count how often each classification is assigned for reasons containing 'death'
fda %>%
  filter(str_detect(tolower(reason_for_recall), "death")) %>%
  count(event_classification) %>%
  arrange(desc(n))
```

```{r}
# View examples of these recall reasons
fda %>%
  filter(str_detect(tolower(reason_for_recall), "death")) %>%
  select(reason_for_recall, event_classification) %>%
  head(10)
```

## Save Trained Model

```{r}
dir.create("4_model-api", showWarnings = FALSE)
saveRDS(recall_fit, "4_model-api/recall_model.rds")
```
